### ISSUE TITLE
Compiled CLI Binary Fails to Run on Older CPUs

### ISSUE THREAD

**Issue by 0zl** [Factory-AI/factory#186]
The Droid/Factory CLI compiled binary appears to be built with Bun for Haswell CPU architecture, which lacks support for older CPUs. Running `droid` produces no output and force-closes. Providing a `baseline`[^1] build flavor would resolve this. Maybe.

Potentially related issues: #111, #156, #170, #184.

[^1]: https://bun.com/docs/installation#cpu-requirements-and-baseline-builds

**Comment by factory-ben** [comment]
can you check now - i believe a fix was pushed in latest update

**Comment by 0zl** [comment]
> can you check now - i believe a fix was pushed in latest update

I'm reinstalling with `irm https://app.factory.ai/cli/windows | iex`, but the issue persists as my older CPU lacks AVX2. Additional `baseline` build could fix this by checking for AVX2 before downloading the binary. Or, you could close this and keep Droid for newer CPUs, which is totally fine.

<img width="304" height="67" alt="Image" src="https://github.com/user-attachments/assets/66153afb-cded-4ff9-8d09-5685e6b4a171" />
