### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by dusancv22** [Factory-AI/factory#256]
https://s3.us-east-1.amazonaws.com/exercise.files/Temp+Download/login_01.png

I just installed Droid on Windows, and when I typed "Droid", I just had the option to "Login" and "Exit".

When I click on "Login", I just get a warning:
Authentication failed:
Was there a typo in the url or port?

What is the issue here?

**Comment by factory-ben** [comment]
should be working now!

**Comment by dusancv22** [comment]
@factory-ben hmmm, still the same on my side.
I reinstalled it completely, used "irm https://app.factory.ai/cli/windows | iex"
When I open it, it says version v0.22.3, but when I just see Login and Exit.
When I click on Login, I get the same issue:
Authentication failed:
Was there a typo in the url or port?
